# Docker compose file for production environment

version: '3.2'

services:
  web:
    build:
      args:
        ARCH: 'arm32v7/'

    image: davla/misc:wiki-spacing-web-prod

    volumes:
      - type: volume
        target: /usr/src/app

  db:
    build:
      args:
        ARCH: 'arm32v7/'

    image: davla/misc:wiki-spacing-db-prod
