# Docker compose file for production environment

version: '3.2'

services:
  web:
    build:
      dockerfile: Dockerfile-test

    image: davla/misc:wiki-spacing-web-test

    restart: "no"

  db:
    image: davla/misc:wiki-spacing-db-test
