# Base docker compose file, that the others are meant to override.
# Used for development environment.

version: '3.2'

services:
  web:
    build:
      args:
        ARCH: ''
      context: server

    depends_on:
      - db

    environment:
      DB_PORT:
      WEB_PORT:

    image: davla/misc:wiki-spacing-web-dev

    ports:
      - target: $WEB_PORT
        published: '13980'

    restart: on-failure

    volumes:
      - type: bind
        source: ./server
        target: /usr/src/app

  db:
    build:
      args:
        ARCH: ''
      context: db

    image: davla/misc:wiki-spacing-db-dev

    ports:
      - target: '5432'
        published: $DB_PORT

    restart: on-failure

    volumes:
      - type: volume
        target: /var/lib/postgresql/data
